// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("axios");
var Json_decode = require("bs-json/src/Json_decode.js");
var ApiChecker$BsApiChecker = require("../src/ApiChecker.bs.js");

function book(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.string, json),
          /* title */Json_decode.field("title", Json_decode.string, json),
          /* description */Json_decode.field("description", Json_decode.string, json),
          /* price */Json_decode.field("price", Json_decode.$$float, json),
          /* tags */Json_decode.field("tags", (function (param) {
                  return Json_decode.array(Json_decode.string, param);
                }), json)
        ];
}

function books() {
  return (function (param) {
      return Json_decode.array(book, param);
    });
}

var Decode = /* module */[
  /* book */book,
  /* books */books
];

var config = {
  baseURL: "http://localhost:3000"
};

var axiosInstance = Axios.create(config);

ApiChecker$BsApiChecker.check("Book details", axiosInstance.get("/books/1"), book);

ApiChecker$BsApiChecker.check("Books root", axiosInstance.get("/books"), books);

exports.Decode = Decode;
exports.config = config;
exports.axiosInstance = axiosInstance;
/* axiosInstance Not a pure module */
