// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Json = require("bs-json/src/Json.js");
var Curry = require("bs-platform/lib/js/curry.js");

function checkStruct(data, decoder) {
  Curry._1(decoder, Json.parseOrRaise(Json.stringify(data)));
  return /* () */0;
}

function check(name, promise, decoder) {
  promise.then((function (response) {
            checkStruct(response.data, decoder);
            return Promise.resolve(/* () */0);
          })).catch((function (error) {
          console.log("Endpoint " + name);
          console.log(error);
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

exports.checkStruct = checkStruct;
exports.check = check;
/* No side effect */
